### ISSUE TITLE
Warning Message on Server Startup

### ISSUE THREAD

**Issue by Alusionary** [PanSzelescik/proxy-protocol-support#3]
When I launch my Fabric server this message is the first to come up:

[ForkJoinPool-1-worker-8/WARN]: Mod io_netty_netty-codec-haproxy uses the version 4.1.78.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

The server still starts, but I'm guessing the proxy isn't working.

I am using the latest version of the Fabric loader and launcher for 1.19.2. Proxy Protocol is enabled on TCPShield.

Any help would be greatly appreciated!

**Comment by PanSzelescik** [comment]
This warning is about the fact that the library for HAProxy does not use semantic version. It can be safely ignored.

I checked the latest version 1.0.4 and it works with:
- Minecraft 1.21.1
- Fabric Loader 0.16.3
- Java 21
- No Fabric API
- No other mods
- TCPShield
- Enabled `whitelistTCPShieldServers` in config

Version 1.0.3 should also work
